### ISSUE TITLE
RK256 tries to cache incomplete blocks

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [nauful/NLZM#1]
It's a bug: https://github.com/nauful/NLZM/blob/dec9d3426a9b7ba696bf128991a3a8be27e0b772/NLZM.cpp#L2073

You access memory before buffer start and anyway you can't meaningfully address 256-byte block before you computed hash of entire 256 bytes

**Comment by nauful** [comment]
That situation doesn't happen AFAIK:
1. rh_end is never zero when tested (always incremented from initial zero in the previous line).
2. rh_end will not overflow because of ShiftLeft and 1G max window size.

I have tried this in multiple scenarios and it's always a multiple of 256 and greater than zero. Please show me an edge case and I can investigate if there's a failure.

I tried replacing all instances of "if (!(rh_end & BLOCK_MASK)) {" with "if (!(rh_end & BLOCK_MASK)) { ASSERT(rh_end > 0);" and tried in compress_opt (every p is visited) and compress_fast (many p are skipped, skipped length is often >256). Handling the latter case (not every p is visited) makes the logic trickier.

**Comment by Bulat-Ziganshin** [comment]
you are right - you need that at the end of block, i.e. when rh_end == BLOCK_MASK
